FROM gcr.io/google-appengine/debian10@sha256:d2e40ef81a0f353f1b9c3cf07e384a1f23db3acdaa0eae4c269b653ab45ffadf as base
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/Los_Angeles
RUN apt-get -y update
RUN apt-get -y install \
	wget pkg-config zip \
	g++ zlib1g-dev unzip python3 \
	git make bash-completion \
	python apt-utils gnupg2 \
	software-properties-common

# install java for bazel
RUN mkdir -p /usr/share/man/man1/
RUN wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
RUN add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
RUN apt-get -y update
RUN apt-get -y install adoptopenjdk-8-hotspot

# install python3 distutils for bazel
RUN apt-get -y install python3-distutils
RUN apt-get install --fix-broken

# install bazel
RUN wget https://github.com/bazelbuild/bazel/releases/download/0.29.1/bazel_0.29.1-linux-x86_64.deb
RUN dpkg -i bazel_0.29.1-linux-x86_64.deb


FROM base as builder
COPY . /workspace
WORKDIR /workspace
RUN bazel build --jobs=5 --local_ram_resources=HOST_RAM*.5 --local_cpu_resources=HOST_CPUS*1 //zetasql/server --verbose_failures


FROM gcr.io/google-appengine/debian10@sha256:d2e40ef81a0f353f1b9c3cf07e384a1f23db3acdaa0eae4c269b653ab45ffadf
RUN mkdir -p /opt/zetasql
RUN groupadd -g 999 zetasql && \
    useradd -r -u 999 -g zetasql zetasql
COPY --from=builder /workspace/bazel-bin/zetasql/server/server /opt/zetasql/server
RUN chown -R zetasql:zetasql /opt/zetasql
EXPOSE 5000
USER zetasql
CMD ["/opt/zetasql/server", "--listen_address", "0.0.0.0:5000"]
